### ISSUE TITLE
Allow offline usage / Generate Lipsum text locally

### ISSUE THREAD

**Issue by Alhadis** [traviskaufman/node-lipsum#3]
It'd be really nice to generate lipsum text without having to use an HTTP request... after downloading this, I assumed it generated the dummy text from locally-cached resources. Instead, it simply made a call to lipsum.com and showed me the results... or tried to, should I say, since I was working offline at the time. It's *because* I had to work offline that I downloaded it...

**Comment by traviskaufman** [comment]
I think then that you may have misunderstood the purpose of this module ;)
it's actually just a wrapper around the http://lipsum.org api service,
which is what does the actual dummy text generation. Check out
https://github.com/knicklabs/lorem-ipsum.js

**Comment by Alhadis** [comment]
Ah crap, the error is mine then. :( My bad, sorry.

Thanks for the link!

**Comment by traviskaufman** [comment]
No worries! :D

**Comment by emotality** [comment]
Any chance that the public can also post and receive response in json? Would like to do something for iOS developers as we also need dummy text sometimes in place of user comments in feeds etc.
